### ISSUE TITLE
Should it be self.hmi_dir instead? 

### ISSUE THREAD

**Issue by joannalcy** [stanfordcr2c/cr2c-monitoring#1]
https://github.com/stanfordcr2c/cr2c-monitoring/blob/380c99aee9ccb0109da6167cf8c833e3cbb4ad69/hmi_data_agg.py#L70
https://github.com/stanfordcr2c/cr2c-monitoring/blob/380c99aee9ccb0109da6167cf8c833e3cbb4ad69/hmi_data_agg.py#L73

**Comment by jbolorinos** [comment]
Yes it should be, good catch
